In [37]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [38]:
df = pd.read_csv(r"C:\Users\USER\Downloads\drugs.csv")

Load Data and understand the Dataset:

The dataset is loaded using Pandas and examined to understand its structure, number of observations, variables, data types, and missing values.

In [6]:
df.head()

,State,Year,Population.12-17,Population.18-25,Population.26+,Totals.Alcohol.Use Disorder Past Year.12-17,Totals.Alcohol.Use Disorder Past Year.18-25,Totals.Alcohol.Use Disorder Past Year.26+,Rates.Alcohol.Use Disorder Past Year.12-17,Rates.Alcohol.Use Disorder Past Year.18-25,...,Totals.Marijuana.Used Past Year.26+,Rates.Marijuana.Used Past Year.12-17,Rates.Marijuana.Used Past Year.18-25,Rates.Marijuana.Used Past Year.26+,Totals.Tobacco.Use Past Month.12-17,Totals.Tobacco.Use Past Month.18-25,Totals.Tobacco.Use Past Month.26+,Rates.Tobacco.Use Past Month.12-17,Rates.Tobacco.Use Past Month.18-25,Rates.Tobacco.Use Past Month.26+
0,Alabama,2002,380805,499453,2812905,18,68,138,48.336,136.490,...,141,127.535,237.880,50.275,63,226,930,166.578,451.976,330.659
1,Alaska,2002,69400,62791,368460,4,12,27,61.479,187.891,...,46,188.730,389.026,124.566,11,30,112,163.918,484.270,304.220
2,Arizona,2002,485521,602265,3329482,36,117,258,73.819,193.626,...,215,169.646,275.435,64.640,73,240,1032,151.071,397.968,309.969
3,Arkansas,2002,232986,302029,1687337,14,53,101,61.457,175.913,...,104,157.567,288.856,61.510,46,169,660,195.714,558.846,391.210
4,California,2002,3140739,3919577,21392421,173,581,1298,55.109,148.312,...,1670,141.067,282.887,78.068,290,1377,4721,92.235,351.353,220.699

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 867 entries, 0 to 866
Data columns (total 53 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   State                                              867 non-null    object
 1   Year                                               867 non-null    int64
 2   Population.12-17                                   867 non-null    int64
 3   Population.18-25                                   867 non-null    int64
 4   Population.26+                                     867 non-null    int64
 5   Totals.Alcohol.Use Disorder Past Year.12-17        867 non-null    int64
 6   Totals.Alcohol.Use Disorder Past Year.18-25        867 non-null    int64
 7   Totals.Alcohol.Use Disorder Past Year.26+          867 non-null    int64
 8   Rates.Alcohol.Use Disorder Past Year.12-17         867 non-null    float64
 9   Rates.Alcohol.Use Disorder Past Year.18-25         867 non-null    float64
 10  Rates.Alcohol.Use Disorder Past Year.26+           867 non-null    float64
 11  Totals.Alcohol.Use Past Month.12-17                867 non-null    int64
 12  Totals.Alcohol.Use Past Month.18-25                867 non-null    int64
 13  Totals.Alcohol.Use Past Month.26+                  867 non-null    int64
 14  Rates.Alcohol.Use Past Month.12-17                 867 non-null    float64
 15  Rates.Alcohol.Use Past Month.18-25                 867 non-null    float64
 16  Rates.Alcohol.Use Past Month.26+                   867 non-null    float64
 17  Totals.Tobacco.Cigarette Past Month.12-17          867 non-null    int64
 18  Totals.Tobacco.Cigarette Past Month.18-25          867 non-null    int64
 19  Totals.Tobacco.Cigarette Past Month.26+            867 non-null    int64
 20  Rates.Tobacco.Cigarette Past Month.12-17           867 non-null    float64
 21  Rates.Tobacco.Cigarette Past Month.18-25           867 non-null    float64
 22  Rates.Tobacco.Cigarette Past Month.26+             867 non-null    float64
 23  Totals.Illicit Drugs.Cocaine Used Past Year.12-17  867 non-null    int64
 24  Totals.Illicit Drugs.Cocaine Used Past Year.18-25  867 non-null    int64
 25  Totals.Illicit Drugs.Cocaine Used Past Year.26+    867 non-null    int64
 26  Rates.Illicit Drugs.Cocaine Used Past Year.12-17   867 non-null    float64
 27  Rates.Illicit Drugs.Cocaine Used Past Year.18-25   867 non-null    float64
 28  Rates.Illicit Drugs.Cocaine Used Past Year.26+     867 non-null    float64
 29  Totals.Marijuana.New Users.12-17                   867 non-null    int64
 30  Totals.Marijuana.New Users.18-25                   867 non-null    int64
 31  Totals.Marijuana.New Users.26+                     867 non-null    int64
 32  Rates.Marijuana.New Users.12-17                    867 non-null    float64
 33  Rates.Marijuana.New Users.18-25                    867 non-null    float64
 34  Rates.Marijuana.New Users.26+                      867 non-null    float64
 35  Totals.Marijuana.Used Past Month.12-17             867 non-null    int64
 36  Totals.Marijuana.Used Past Month.18-25             867 non-null    int64
 37  Totals.Marijuana.Used Past Month.26+               867 non-null    int64
 38  Rates.Marijuana.Used Past Month.12-17              867 non-null    float64
 39  Rates.Marijuana.Used Past Month.18-25              867 non-null    float64
 40  Rates.Marijuana.Used Past Month.26+                867 non-null    float64
 41  Totals.Marijuana.Used Past Year.12-17              867 non-null    int64
 42  Totals.Marijuana.Used Past Year.18-25              867 non-null    int64
 43  Totals.Marijuana.Used Past Year.26+                867 non-null    int64
 44  Rates.Marijuana.Used Past Year.12-17               867 non-null    float64
 45  Rates.Marijuana.Used Past Year.18-25               867 non-null    float64
 46  Rates.Marijuana.Used Past Year.26+                 867 non-null    float64
 47  Totals.Tobacco.Use Past Month.12-17                867 non-null    int64
 48  Totals.Tobacco.Use Past Month.18-25                867 non-null    int64
 49  Totals.Tobacco.Use Past Month.26+                  867 non-null    int64
 50  Rates.Tobacco.Use Past Month.12-17                 867 non-null    float64
 51  Rates.Tobacco.Use Past Month.18-25                 867 non-null    float64
 52  Rates.Tobacco.Use Past Month.26+                   867 non-null    float64
dtypes: float64(24), int64(28), object(1)
memory usage: 359.1+ KB

In [8]:
df.shape

(867, 53)

In [9]:
df.isnull().sum()

State                                                0
Year                                                 0
Population.12-17                                     0
Population.18-25                                     0
Population.26+                                       0
Totals.Alcohol.Use Disorder Past Year.12-17          0
Totals.Alcohol.Use Disorder Past Year.18-25          0
Totals.Alcohol.Use Disorder Past Year.26+            0
Rates.Alcohol.Use Disorder Past Year.12-17           0
Rates.Alcohol.Use Disorder Past Year.18-25           0
Rates.Alcohol.Use Disorder Past Year.26+             0
Totals.Alcohol.Use Past Month.12-17                  0
Totals.Alcohol.Use Past Month.18-25                  0
Totals.Alcohol.Use Past Month.26+                    0
Rates.Alcohol.Use Past Month.12-17                   0
Rates.Alcohol.Use Past Month.18-25                   0
Rates.Alcohol.Use Past Month.26+                     0
Totals.Tobacco.Cigarette Past Month.12-17            0
Totals.Tobacco.Cigarette Past Month.18-25            0
Totals.Tobacco.Cigarette Past Month.26+              0
Rates.Tobacco.Cigarette Past Month.12-17             0
Rates.Tobacco.Cigarette Past Month.18-25             0
Rates.Tobacco.Cigarette Past Month.26+               0
Totals.Illicit Drugs.Cocaine Used Past Year.12-17    0
Totals.Illicit Drugs.Cocaine Used Past Year.18-25    0
Totals.Illicit Drugs.Cocaine Used Past Year.26+      0
Rates.Illicit Drugs.Cocaine Used Past Year.12-17     0
Rates.Illicit Drugs.Cocaine Used Past Year.18-25     0
Rates.Illicit Drugs.Cocaine Used Past Year.26+       0
Totals.Marijuana.New Users.12-17                     0
Totals.Marijuana.New Users.18-25                     0
Totals.Marijuana.New Users.26+                       0
Rates.Marijuana.New Users.12-17                      0
Rates.Marijuana.New Users.18-25                      0
Rates.Marijuana.New Users.26+                        0
Totals.Marijuana.Used Past Month.12-17               0
Totals.Marijuana.Used Past Month.18-25               0
Totals.Marijuana.Used Past Month.26+                 0
Rates.Marijuana.Used Past Month.12-17                0
Rates.Marijuana.Used Past Month.18-25                0
Rates.Marijuana.Used Past Month.26+                  0
Totals.Marijuana.Used Past Year.12-17                0
Totals.Marijuana.Used Past Year.18-25                0
Totals.Marijuana.Used Past Year.26+                  0
Rates.Marijuana.Used Past Year.12-17                 0
Rates.Marijuana.Used Past Year.18-25                 0
Rates.Marijuana.Used Past Year.26+                   0
Totals.Tobacco.Use Past Month.12-17                  0
Totals.Tobacco.Use Past Month.18-25                  0
Totals.Tobacco.Use Past Month.26+                    0
Rates.Tobacco.Use Past Month.12-17                   0
Rates.Tobacco.Use Past Month.18-25                   0
Rates.Tobacco.Use Past Month.26+                     0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.describe()

,Year,Population.12-17,Population.18-25,Population.26+,Totals.Alcohol.Use Disorder Past Year.12-17,Totals.Alcohol.Use Disorder Past Year.18-25,Totals.Alcohol.Use Disorder Past Year.26+,Rates.Alcohol.Use Disorder Past Year.12-17,Rates.Alcohol.Use Disorder Past Year.18-25,Rates.Alcohol.Use Disorder Past Year.26+,...,Totals.Marijuana.Used Past Year.26+,Rates.Marijuana.Used Past Year.12-17,Rates.Marijuana.Used Past Year.18-25,Rates.Marijuana.Used Past Year.26+,Totals.Tobacco.Use Past Month.12-17,Totals.Tobacco.Use Past Month.18-25,Totals.Tobacco.Use Past Month.26+,Rates.Tobacco.Use Past Month.12-17,Rates.Tobacco.Use Past Month.18-25,Rates.Tobacco.Use Past Month.26+
count,867.000000,8.670000e+02,8.670000e+02,8.670000e+02,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,...,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000,867.000000
mean,2010.000000,4.897141e+05,6.588800e+05,3.874155e+06,19.224913,94.482122,224.147636,40.949511,151.180014,59.767603,...,348.762399,138.027751,314.068905,91.916272,47.513264,249.241061,1029.912341,106.241322,402.758178,279.926587
std,4.901807,5.637959e+05,7.559898e+05,4.320776e+06,25.290532,108.272774,254.022992,18.241042,38.558341,9.945844,...,449.851031,25.662836,66.664587,37.791885,51.334800,253.201192,1001.450163,42.548930,79.266735,47.035776
min,2002.000000,3.055100e+04,5.739500e+04,3.101100e+05,0.000000,6.000000,19.000000,12.143000,71.218000,33.838000,...,17.000000,85.626000,168.109000,37.015000,1.000000,18.000000,95.000000,22.002000,165.110000,149.708000
25%,2006.000000,1.315405e+05,1.742935e+05,1.027871e+06,5.000000,26.000000,57.500000,25.502500,120.067000,53.102500,...,91.500000,118.743000,268.399500,65.944500,13.000000,67.500000,258.500000,71.691500,347.555500,250.471500
50%,2010.000000,3.396850e+05,4.562400e+05,2.698757e+06,11.000000,64.000000,154.000000,38.740000,148.268000,59.553000,...,212.000000,134.376000,300.243000,81.496000,31.000000,181.000000,828.000000,106.260000,416.882000,279.497000
75%,2014.000000,5.410950e+05,7.468080e+05,4.509094e+06,24.000000,119.500000,271.500000,53.899500,177.735500,65.754000,...,439.500000,156.350000,353.077500,106.036000,62.000000,313.000000,1289.000000,136.697500,464.039500,311.211000
max,2018.000000,3.293484e+06,4.469106e+06,2.591772e+07,204.000000,717.000000,1586.000000,112.131000,272.941000,112.720000,...,4476.000000,226.901000,532.019000,254.779000,358.000000,1488.000000,5099.000000,243.006000,588.839000,409.574000

In [12]:
df.dtypes

State                                                 object
Year                                                   int64
Population.12-17                                       int64
Population.18-25                                       int64
Population.26+                                         int64
Totals.Alcohol.Use Disorder Past Year.12-17            int64
Totals.Alcohol.Use Disorder Past Year.18-25            int64
Totals.Alcohol.Use Disorder Past Year.26+              int64
Rates.Alcohol.Use Disorder Past Year.12-17           float64
Rates.Alcohol.Use Disorder Past Year.18-25           float64
Rates.Alcohol.Use Disorder Past Year.26+             float64
Totals.Alcohol.Use Past Month.12-17                    int64
Totals.Alcohol.Use Past Month.18-25                    int64
Totals.Alcohol.Use Past Month.26+                      int64
Rates.Alcohol.Use Past Month.12-17                   float64
Rates.Alcohol.Use Past Month.18-25                   float64
Rates.Alcohol.Use Past Month.26+                     float64
Totals.Tobacco.Cigarette Past Month.12-17              int64
Totals.Tobacco.Cigarette Past Month.18-25              int64
Totals.Tobacco.Cigarette Past Month.26+                int64
Rates.Tobacco.Cigarette Past Month.12-17             float64
Rates.Tobacco.Cigarette Past Month.18-25             float64
Rates.Tobacco.Cigarette Past Month.26+               float64
Totals.Illicit Drugs.Cocaine Used Past Year.12-17      int64
Totals.Illicit Drugs.Cocaine Used Past Year.18-25      int64
Totals.Illicit Drugs.Cocaine Used Past Year.26+        int64
Rates.Illicit Drugs.Cocaine Used Past Year.12-17     float64
Rates.Illicit Drugs.Cocaine Used Past Year.18-25     float64
Rates.Illicit Drugs.Cocaine Used Past Year.26+       float64
Totals.Marijuana.New Users.12-17                       int64
Totals.Marijuana.New Users.18-25                       int64
Totals.Marijuana.New Users.26+                         int64
Rates.Marijuana.New Users.12-17                      float64
Rates.Marijuana.New Users.18-25                      float64
Rates.Marijuana.New Users.26+                        float64
Totals.Marijuana.Used Past Month.12-17                 int64
Totals.Marijuana.Used Past Month.18-25                 int64
Totals.Marijuana.Used Past Month.26+                   int64
Rates.Marijuana.Used Past Month.12-17                float64
Rates.Marijuana.Used Past Month.18-25                float64
Rates.Marijuana.Used Past Month.26+                  float64
Totals.Marijuana.Used Past Year.12-17                  int64
Totals.Marijuana.Used Past Year.18-25                  int64
Totals.Marijuana.Used Past Year.26+                    int64
Rates.Marijuana.Used Past Year.12-17                 float64
Rates.Marijuana.Used Past Year.18-25                 float64
Rates.Marijuana.Used Past Year.26+                   float64
Totals.Tobacco.Use Past Month.12-17                    int64
Totals.Tobacco.Use Past Month.18-25                    int64
Totals.Tobacco.Use Past Month.26+                      int64
Rates.Tobacco.Use Past Month.12-17                   float64
Rates.Tobacco.Use Past Month.18-25                   float64
Rates.Tobacco.Use Past Month.26+                     float64
dtype: object

In [13]:
print (df["State"])

0            Alabama
1             Alaska
2            Arizona
3           Arkansas
4         California
           ...
862         Virginia
863       Washington
864    West Virginia
865        Wisconsin
866          Wyoming
Name: State, Length: 867, dtype: object

In [14]:
df["State"] = df["State"].str.strip()

In [15]:
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

In [16]:
df = df.drop_duplicates()

In [17]:
print("Dataset shape after cleaning:", df.shape)

Dataset shape after cleaning: (867, 53)

The data shape remains the same because our data set has no missing values or duplicate values.

In [26]:
df_transformed.shape

(867, 103)

Feature Engineering

Two new features are created for this analysis. Firstly, an average substance-use rate is calculated from alcohol use disorder, cocaine use,and tobacco use among individuals aged 18–25. This feature provides a combined measure of other substance-use patterns that may be associated with marijuana use.

Secondly, a young-adult population ratio is created by dividing the population aged 18–25 by the total population represented by the three age groups (12–17, 18–25, and 26+). This transforms the population counts into a proportion and provides information about the relative size of the 18–25 age group.

In [50]:
df["Average_Other_Substance_Use_Rate_18_25"] = df[
    [
        "Rates.Alcohol.Use Disorder Past Year.18-25",
        "Rates.Illicit Drugs.Cocaine Used Past Year.18-25",
        "Rates.Tobacco.Use Past Month.18-25"
    ]
].mean(axis=1)

In [52]:
df["Young_Adult_Population_Ratio"] = (
    df["Population.18-25"] /
    (
        df["Population.12-17"] +
        df["Population.18-25"] +
        df["Population.26+"]
    )
)

In [53]:
df[
    [
        "Rates.Alcohol.Use Disorder Past Year.18-25",
        "Rates.Illicit Drugs.Cocaine Used Past Year.18-25",
        "Rates.Tobacco.Use Past Month.18-25",
        "Average_Other_Substance_Use_Rate_18_25",
        "Young_Adult_Population_Ratio"
    ]
].head()

,Rates.Alcohol.Use Disorder Past Year.18-25,Rates.Illicit Drugs.Cocaine Used Past Year.18-25,Rates.Tobacco.Use Past Month.18-25,Average_Other_Substance_Use_Rate_18_25,Young_Adult_Population_Ratio
0,136.490,54.892,451.976,214.452667,0.135237
1,187.891,83.680,484.270,251.947000,0.125419
2,193.626,85.300,397.968,225.631333,0.136343
3,175.913,60.500,558.846,265.086333,0.135905
4,148.312,66.052,351.353,188.572333,0.137757

Define Features and Target

The target variable for this machine learning task is the rate of marijuana use in the past year among individuals aged 18–25.The selected features include state, year, young adult popuulation ratio, alcohol use disorder, cocaine use, and tobacco use among the same age group.

In [54]:
features = [
    "State",
    "Year",
    "Young_Adult_Population_Ratio",
    "Rates.Alcohol.Use Disorder Past Year.18-25",
    "Rates.Illicit Drugs.Cocaine Used Past Year.18-25",
    "Rates.Tobacco.Use Past Month.18-25"
]

X = df[features]
y = df["Rates.Marijuana.Used Past Year.18-25"]

In [55]:
print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
        State  Year  Young_Adult_Population_Ratio  \
0     Alabama  2002                      0.135237
1      Alaska  2002                      0.125419
2     Arizona  2002                      0.136343
3    Arkansas  2002                      0.135905
4  California  2002                      0.137757

   Rates.Alcohol.Use Disorder Past Year.18-25  \
0                                     136.490
1                                     187.891
2                                     193.626
3                                     175.913
4                                     148.312

   Rates.Illicit Drugs.Cocaine Used Past Year.18-25  \
0                                            54.892
1                                            83.680
2                                            85.300
3                                            60.500
4                                            66.052

   Rates.Tobacco.Use Past Month.18-25
0                             451.976
1                             484.270
2                             397.968
3                             558.846
4                             351.353

Target:
0    237.880
1    389.026
2    275.435
3    288.856
4    282.887
Name: Rates.Marijuana.Used Past Year.18-25, dtype: float64

Train/Test Split
The dataset is divided into training and testing sets using an 80/20 split respectively. The training data will be used to learn the preprocessing parameters and train the machine learning model, while the test data will be reserved for final evaluation.
A random state of 42 is used to ensure that the same split can be reproduced.

In [56]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.20,random_state=42)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (693, 6)
Testing data: (174, 6)

Identify Feature Types
The selected features are divided into numerical and categorical variables.
Numerical features include year, young adult population, alcohol use disorder, cocaine use, and tobacco use. These variables require numerical preprocessing.
State is treated as a categorical feature because it represents differentstate categories rather than a continuous numerical measurement. It will be encoded using one-hot encoding.

In [59]:
numeric_features = [
    "Year",
    "Young_Adult_Population_Ratio",
    "Rates.Alcohol.Use Disorder Past Year.18-25",
    "Rates.Illicit Drugs.Cocaine Used Past Year.18-25",
    "Rates.Tobacco.Use Past Month.18-25"
]

categorical_features = ["State"]

Numerical Feature Preprocessing

The numerical features are processed using a two-step pipeline. The missing numerical values are replaced with the median value (it is less sensitive to outliers) of the corresponding feature,then standardScaler is used to standardize the numerical variables so that they are placed on a comparable scale.

The preprocessing steps are fitted using the training data to avoid data leakage.

In [60]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

Categorical Feature Preprocessing

The State variable is categorical, so OneHotEncoder is used to transform each state into numerical binary features.The missing values are replaced with the most frequent state and the 'handle_unknown="ignore"' option ensures that the preprocessing pipeline does not produce an error if a category appears in the test data that was not present in the training data.

In [61]:
categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

Combine Preprocessing Steps

ColumnTransformer is used to apply the appropriate preprocessing method to each type of feature.
Numerical variables are passed through the numerical preprocessing pipeline, and the State variable is passed through the categorical pipeline, where it is one-hot encoded.

In [62]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [63]:
X_train_processed = preprocessor.fit_transform(X_train)

print("Original Training Data Shape:", X_train.shape)
print("Processed Training Data Shape:", X_train_processed.shape)

Original Training Data Shape: (693, 6)
Processed Training Data Shape: (693, 56)

In [64]:
X_test_processed = preprocessor.transform(X_test)

print("Original Testing Data Shape:", X_test.shape)
print("Processed Testing Data Shape:", X_test_processed.shape)

Original Testing Data Shape: (174, 6)
Processed Testing Data Shape: (174, 56)

The machine learning pipeline is trained using the training dataset. The pipeline contains both the preprocessing steps and the Linear Regression model. Using the pipeline ensures that the preprocessing operations are fitted only on the training data. This helps prevent data leakage because information from the test dataset is not used during the training process.

In [65]:
from sklearn.linear_model import LinearRegression

model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

In [66]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Year',
                                                   'Young_Adult_Population_Ratio',
                                                   'Rates.Alcohol.Use Disorder '
                                                   'Past Year.18-25',
                                                   'Rates.Illicit '
                                                   'Drugs.Cocaine Used Past '
                                                   'Year.18-25',
                                                   'Rates.Tobacco.Use Past '
                                                   'Month.18-25']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['State'])])),
                ('regressor', LinearRegression())])

A 5-fold cross-validation is performed on the training dataset, the training data is divided into five subsets,and the model is trained on four folds and validated on the remaining fold. This process is repeated five times so that each fold is used as the validation set once.

This helps determine whether the model performs consistently across different subsets of the training data and reduces the possibility of relying on a single train-validation split. The test dataset remains untouched during cross-validation and is reserved for the final evaluation of the trained model.

In [69]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    model,
    X_train,
    y_train,
    cv=5,
    scoring="r2"
)

print("Cross-validation scores:", cv_scores)
print("Mean CV score:", cv_scores.mean())

Cross-validation scores: [0.87238051 0.91008496 0.89316609 0.90065781 0.84554001]
Mean CV score: 0.8843658757785974

In [70]:
y_pred = model.predict(X_test)

In [71]:
results = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": y_pred
})
results.head()

    Actual   Predicted
0  328.703  319.991365
1  283.836  281.011707
2  239.584  241.165901
3  357.991  339.463242
4  388.969  380.564676

Model Evaluation
The trained model is evaluated using the test dataset.The evaluation metrics used are Mean Absolute Error (MAE), Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and R² Score.

In [72]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 17.76711940014197
MSE: 566.0173470509997
RMSE: 23.791119079417
R²: 0.8703477286774512

In [73]:
print("Mean CV R²:", cv_scores.mean())
print("Test R²:", r2)

Mean CV R²: 0.8843658757785974
Test R²: 0.8703477286774512

Overall, the model demonstrates a relatively strong predictive performance based on the R² score. However, the MAE and RMSE indicate that some prediction errors remain.The model performed similarly during cross-validation and on the test set. The small difference suggests that the model's performance is fairly consistent and that there isn't a major indication of overfitting.